name: Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[async,test]
      - name: Run linters
        run: |
          ruff check .
          mypy src/scriptdb
      - name: Run tests
        run: pytest
